### ISSUE TITLE
Doesn't work with python 3.10.x

### ISSUE THREAD

**Issue by forgedhallpass** [Tib3rius/AutoRecon#175]
After a Kali update, that included an upgrade to python 3.10.x, it doesn't work anymore because of a breaking change:

```
cannot import portscan-all-tcp-ports.py plugin
cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py
```

**Comment by forgedhallpass** [comment]
### Workaround
It works with the following changes in `urllib3`:

1. In `/usr/local/lib/python3.10/dist-packages/urllib3/util/selectors.py` change 
```python
from collections import namedtuple, Mapping
```
to:
```python
from collections import namedtuple
from collections.abc import Mapping
```

2. In `/usr/local/lib/python3.10/dist-packages/urllib3/_collections.py` change 
```python
from collections import Mapping, MutableMapping
```
 to:
```python
from collections.abc import Mapping, MutableMapping
```

**Comment by Tib3rius** [comment]
Hi @forgedhallpass,

I installed Python 3.10.4 on my Kali and AutoRecon is working fine. I'm not quite sure how you are getting that error, the collections library is not used by that plugin directly so I imagine a dependency is using it.

Could you try upgrading your installed python packages using this command:

```
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
```

Your current solution involves editing a standard python library which is not recommended as it will likely break other applications.
